name: Changes to the index.html file
run-name: ${{ github.actor }} has made changes to the index file
on:
  push:
    paths:
      - 'index.html'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_dir: ./
