name: Changes to the index.html file
run-name: ${{ github.actor }} has made changes to the index file
#Runs only when there are changes to the 'index.html' file
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    #Sets up the enviroment (ubuntu latest)
    runs-on: ubuntu-latest
    steps:
      #Checks the code(?)
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
