name: Changes to the index.html file
run-name: ${{ github.actor }} has made changes to the index file
#Runs only when there are changes to the 'index.html' file
on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
jobs:
  deploy:
    #Sets up the enviroment (ubuntu latest)
    runs-on: ubuntu-latest
    steps:
      #Checks the code(?)
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run a one-line script
      run: echo "Hello, world!"

    - name: Run a multi-line script
      run: |
        echo "Adding more features"
        echo "Even more features"
        echo "Meow"
